export const dataProduct = [
    {
        id: 1,
        name: "Lentes CharlesDeLuvio",
        urlImages: "./images/products/charlesdeluvio-1-nx1QR5dTE-unsplash.jpg",
        stock: 8,
        price: 58,
        category: ["moda"],
    },
    {
        id: 2,
        name: "Reloj Digital DanielKorpai",
        urlImages: "./images/products/daniel-korpai-hbTKIbuMmBI-unsplash.jpg",
        stock: 3,
        price: 70,
        category: ["moda","tecnologia"],
    },
    {
        id: 3,
        name: "Camara Polaroid",
        urlImages: "./images/products/eniko-kis-KsLPTsYaqIQ-unsplash.jpg",
        stock: 5,
        price: 18,
        category: ["tecnologia"],
    },
    {
        id: 4,
        name: "Lentes GiorgioTrovato",
        urlImages: "./images/products/giorgio-trovato-K62u25Jk6vo-unsplash.jpg",
        stock: 18,
        price: 33,
        category: ["moda"],
    },
    {
        id: 5,
        name: "Corneta GrantRitchie",
        urlImages: "./images/products/grant-ritchie-n_wXNttWVGs-unsplash.jpg",
        stock: 2,
        price: 44,
        category: ["tecnologia"],
    },
    {
        id: 6,
        name: "Zapatos Deportivos Irene",
        urlImages: "./images/products/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
        stock: 5,
        price: 50,
        category: ["moda","entrenamiento"],
    },
    {
        id: 7,
        name: "Botella Deportiva",
        urlImages: "./images/products/joan-tran-reEySFadyJQ-unsplash.jpg",
        stock: 10,
        price: 15,
        category: ["entrenamiento"],
    },
    {
        id: 8,
        name: "Combo Limpieza",
        urlImages: "./images/products/kelly-sikkema-xp-ND7NjWaA-unsplash.jpg",
        stock: 11,
        price: 10,
        category: ["industrias","jardin"],
    },
    {
        id: 9,
        name: "Audifonos KiranCK",
        urlImages: "./images/products/kiran-ck-LSNJ-pltdu8-unsplash.jpg",
        stock: 23,
        price: 30,
        category: ["tecnologia"],
    },
    {
        id: 10,
        name: "Bycicle Terminator",
        urlImages: "./images/products/mikkel-bech-yjAFnkLtKY0-unsplash.jpg",
        stock: 11,
        price: 358,
        category: ["entrenamiento","industria"],
    },
    {
        id: 11,
        name: "Tacones Floral Mohammad",
        urlImages: "./images/products/mohammad-metri-E-0ON3VGrBc-unsplash.jpg",
        stock: 1,
        price: 500,
        category: ["moda"],
    },
    {
        id: 12,
        name: "Reloj Digital RACHITANK",
        urlImages: "./images/products/rachit-tank-2cFZ_FB08UM-unsplash.jpg",
        stock: 10,
        price: 123,
        category: ["moda","tecnologia"],
    },
    {
        id: 13,
        name: "Zapatos Deportivos Revolt164",
        urlImages: "./images/products/revolt-164_6wVEHfI-unsplash.jpg",
        stock: 17,
        price: 164,
        category: ["moda","entrenamiento"],
    },
    {
        id: 14,
        name: "Banco de jardín",
        urlImages: "./images/products/ruslan-bardash-4kTbAMRAHtQ-unsplash.jpg",
        stock: 27,
        price: 7,
        category: ["jardin"],
    },
    {
        id: 15,
        name: "Samsung Powerbank Memory",
        urlImages: "./images/products/samsung-memory-k5eFm1f2esQ-unsplash.jpg",
        stock: 41,
        price: 27,
        category: ["tecnologia"],
    },
    {
        id: 16,
        name: "Dron cuatrihelice",
        urlImages: "./images/products/samsung-memory-Mfnv3l9ZDgE-unsplash.jpg",
        stock: 1,
        price: 99,
        category: ["tecnologia"],
    },
    {
        id: 17,
        name: "Cámara fotográfica VarunGaba",
        urlImages: "./images/products/varun-gaba-dcgB3CgidlU-unsplash.jpg",
        stock: 15,
        price: 57,
        category: ["tecnologia"],
    }
]